services:
  web:
    image: 047719623163.dkr.ecr.eu-central-1.amazonaws.com/file-manager-app:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./.env:/var/www/.env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - LOG_GROUP_NAME=${LOG_GROUP_NAME}
      - LOG_ENABLED=${LOG_ENABLED}
