name: Deploy to EC2

on:
  push:
    branches:
      - main
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
  PROJECT_DIR: /opt/app/almarac

jobs:
  build-and-push-to-ecr:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.build-image.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTION }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
          IMAGE_URI: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
        run: |
          echo "--- Starting build and push --- "
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          echo "--- Docker build complete --- "

          echo "--- Pushing SHA-tagged image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --- "
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "--- Pushing latest-tagged image: $ECR_REGISTRY/$ECR_REPOSITORY:latest --- "
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "--- Docker pushes complete --- "

          echo "--- Setting outputs --- "
          echo "Image Tag to set: ${IMAGE_TAG}"

          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "--- Outputs set --- "

  deploy-web-server:
    name: Deploy Web Server
    runs-on: ubuntu-latest
    needs: build-and-push-to-ecr
    if: success() && needs.build-and-push-to-ecr.outputs.image_tag != ''

    steps:
      - name: Deploy to Web Server EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.WEB_SERVER_HOST }}
          username: ${{ secrets.WEB_SERVER_USER }}
          key: ${{ secrets.WEB_SERVER_SSH_KEY }}
          script: |
            set -e # Exit immediately if a command exits with a non-zero status.
            echo "Deploying to Web Server..."
            PROJECT_PATH="${{ env.PROJECT_DIR }}" # Define once

            # Reconstruct the image URI for the SHA-tagged image
            SHA_IMAGE_URI="${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ needs.build-and-push-to-ecr.outputs.image_tag }}"
            LATEST_IMAGE_URI="${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest"

            # Navigate to project directory, or clone if it doesn't exist
            if [ ! -d "$PROJECT_PATH" ]; then
              echo "Cloning repository..."
              git clone https://github.com/${{ github.repository }}.git "$PROJECT_PATH"
              cd "$PROJECT_PATH"
            else
              echo "Repository exists, pulling latest changes..."
              cd "$PROJECT_PATH"
              git checkout main # Or your default branch
              git pull origin main # Or your default branch
            fi

            echo "Creating/Updating .env file for web server..."
            echo "${{ secrets.ENV_FILE_WEB_PROD }}" > "$PROJECT_PATH/.env"

            echo "Logging in to ECR (needed for pull)..."
            aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

            echo "Pulling latest image from ECR..."
            echo "Pulling SHA-tagged image: $SHA_IMAGE_URI"
            docker pull $SHA_IMAGE_URI
            echo "Pulling latest-tagged image: $LATEST_IMAGE_URI"
            docker pull $LATEST_IMAGE_URI

            echo "Stopping and removing old web containers..."
            cd "$PROJECT_PATH" # Ensure we are in the project directory
            if [ -f docker-compose.web.yml ]; then
              docker compose -f docker-compose.web.yml down || echo "No containers were running or compose file issue."
            else
              echo "docker-compose.web.yml not found!"
              exit 1
            fi

            echo "Starting new web containers..."
            # Ensure the .env file provides the correct image tag if needed, or rely on :latest
            # For simplicity, this example assumes docker-compose.web.yml uses image: $ECR_REGISTRY/$ECR_REPOSITORY:latest
            docker compose -f docker-compose.web.yml up -d

            echo "Cleaning up old Docker images..."
            docker image prune -af || echo "Docker image prune failed or no images to prune."

            echo "Web server deployment complete."

  deploy-database-server:
    name: Database Server - MANUAL UPDATE REQUIRED
    runs-on: ubuntu-latest
    needs: build-and-push-to-ecr

    steps:
      - name: Display Manual Instructions for Database Server
        run: |
          echo "-----------------------------------------------------------------"
          echo "MANUAL DEPLOYMENT STEPS REQUIRED FOR DATABASE SERVER:"
          echo "-----------------------------------------------------------------"
          echo "1. Connect to the database server (e.g., via AWS SSM Session Manager)."
          echo "2. Navigate to the project directory: cd ${{ env.PROJECT_DIR }}"
          echo "3. Pull the latest code changes: git pull origin main"
          echo "4. If composer.json changed (unlikely for DB only): composer install"
          echo "5. Update .env file manually if new secrets/configs are needed."
          echo "6. If docker-compose.db.yml or .env changed, restart services:"
          echo "   sudo docker compose -f docker-compose.db.yml down"
          echo "   sudo docker compose -f docker-compose.db.yml up -d"
          echo "-----------------------------------------------------------------"
